### ISSUE TITLE
Config Troubles (Solved, see replies)

### ISSUE THREAD

**Issue by Tvgeekfromthelate2000s** [tim000x3/CommercialBreaker#1]
Yeah, while trying to set this up I got the following error:

D:\CommercialBreaker-main>python3 TOM.py
Traceback (most recent call last):
  File "D:\CommercialBreaker-main\TOM.py", line 665, in <module>
    app = MainApplication()
          ^^^^^^^^^^^^^^^^^
  File "D:\CommercialBreaker-main\TOM.py", line 630, in __init__
    frame = F(parent=container, controller=self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CommercialBreaker-main\TOM.py", line 488, in __init__
    toonami_version_dropdown['values'] = list(TOONAMI_CONFIG.keys())
                                              ^^^^^^^^^^^^^^
NameError: name 'TOONAMI_CONFIG' is not defined

In all seriousness, please help. :(

**Comment by tim000x3** [comment]
Did you run cp example-config.py config.py? The program needs the config.py but only has example-config.py. You can also just rename example-config.py to config.py

**Comment by tim000x3** [comment]
What step were you on when you ran into this? Also did you run "cp example-config.py config.py" You need to either run this or just rename example-config.py to config.py

**Comment by tim000x3** [comment]
We just pushed a new version as well so feel free to try that and see if the issue persists. Just delete your config.py and run cp example-config.py config.py again as the new version has some changes to the config.py

**Comment by Tvgeekfromthelate2000s** [comment]
> What step were you on when you ran into this? Also did you run "cp example-config.py config.py" You need to either run this or just rename example-config.py to config.py

It worked. Thank you! :D
